TIPOS_OBRA = (
    ('CIST', 'Cisterna'),
    ('PMOL', 'Passagem Molhada'),
)

GERENCIAS = (
    ('SOUSA', 'Sousa'),
)

LOTES = (
    ('9', 'Lote 9'),
    ('10','Lote 10')
)

MUNICIPIOS = (
    ('AGU', 'Aguiar'),
    ('APAR', 'Aparecida'),
    ('BBAT', 'Bernardino Batista'),
    ('BSUC', 'Bom Sucesso'),
    ('BDSF', 'Bonito de Santa Fé'),
    ('BBRCZ','Belém do Brejo do Cruz'), 
    ('BRJC', 'Brejo do Cruz'),
    ('BDSS', 'Brejo dos Santos'),
    ('CACH', 'Cachoeira dos Índios'),
    ('CATR', 'Catolé do Rocha'),
    ('MARZ', 'Marizópolis'),
    ('MONH', 'Monte Horebe'),
    ('NAZA', 'Nazarezinho'),
    ('RICA', 'Riacho dos Cavalos'),
    ('SJRP', 'São João do Rio do Peixe'),
    ('SJP',  'São José de Piranhas'),
    ('SOUS', 'Sousa'),
    ('VIEI', 'Vieirópolis'),
    ('CAJZ', 'Cajazeiras'),
    ('MATO', 'Mato Grosso'),
    ('JERI', 'Jericó'),
    ('STHL', 'Santa Helena'),
    ('SJLT', 'São José da Lagoa Tapada'), 
    ('SABE', 'São Bento'), 
    ('SJBC', 'São José do Brejo do Cruz'),
    ('UIRA', 'Uiraúna'),
    ('POJO', 'Poço de José de Moura'),
    ('TRIU', 'Triunfo'),
    ('PMBL', 'Pombal'),
)


# choices.py

ASSOCIACOES = (
    ('ACRR', 'ASSOCIAÇÃO COMUNITÁRIA RURAL DE RIACHÃO'),
    ('ACRJLR', 'ASSOCIAÇÃO COMUNITARIA RURAL JOÃO LUIZ RIBEIRO'),
    ('ACAPB', 'ASSOCIAÇÃO COMUNITÁRIA DOS AGRICULTORES DA PEDRA BRANCA'),
    ('ACSH', 'ASSOCIAÇÃO COMUNITARIA DO SITIO HUMAITÁ'),
    ('ACPA', 'ASSOCIAÇÃO COMUNITÁRIA DOS POSSEIROS DO ASSENTAMENTO BARTOLOMEU'),
    ('ATRB', 'ASSOCIACAO DOS TRABALHADORES RURAIS DO BARTOLOMEU'),
    ('NIR', 'NUCLEO DE INTEGRACAO RURAL'),
    ('ACRAFM', 'ASSOCIAÇÃO COMUNITÁRIA RURAL ALBINO FRANCISCO DA MATA DO SITIO TUBIBA'),
    ('ACRAC', 'ASSOCIAÇÃO COMUNITÁRIA RURAL AGOSTINHO CHAGAS'),
    ('ACSLMB', 'ASSOCIAÇÃO COMUNITÁRIA DO SÍTIO LAGOA DO MATO DOS BELÉM "PROFESSOR" HENRIQUE DE FRANÇA BELÉM'),
    ('ACMLA', 'ASSOCIACAO COMUNITARIA MANOEL LINS DE ALBUQUERQUE'),
    ('ACRA', 'ASSOCIAÇÃO COMUNITÁRIA RURAL DE ALVORADA'),
    ('AADSF', 'ASSOCIAÇÃO DOS AGRICULTORES DO SAO FRANCISCO'),
    ('ACRBS', 'ASSOCIAÇÃO COMUNITÁRIA RURAL DO SÍTIO BODES'),
    ('ACRP', 'ASSOCIAÇÃO COMUNITÁRIA RURAL DO SÍTIO PILAR'),
    ('AGMMFS', 'ASSOCIAÇÃO GRUPO MULHERES MAURINA FRANCISCA DE SOUSA'),
    ('ADESCJBV', 'ASSOCIAÇÃO DE DESENVOLVIMENTO ECONÔMICO SOCIAL DAS COMUNIDADES DO JUCA E BOA VISTA'),
    ('ATRSG', 'ASSOC IAÇÃO DOS TRAB ALHADORES RURAIS DO SÍTIO GRAVATÁ'),
    ('ACSC', 'ASSOCIAÇÃO COMUNITÁRIA DO SÍTIO CARRANCUDO'),
    ('ACRS', 'ASSOCIAÇÃO COMUNITÁRIA RURAL DA SERRINHA'),
    ('ACRVPR', 'ASSOCIAÇÃO COMUNITÁRIA DA VILA PRODUTIVA RURAL VPR LAFAYETTE'),
    ('ACUSMF', 'ASSOCIAÇÃO COMUNITÁRIA "UNIDOS SOMOS MAIS FORTES"'),
    ('AACA', 'ASSOCIAÇÃO DOS AGRICULTORES DE CAATINGA DOS ANDRADE'),
    ('ACRSAA', 'ASSOCIAÇÃO COMUNITÁRIA RURAL DE SANTANA DOS ALMEIDAS'),
    ('ADSPV', 'ASSOCIAÇÃO DE DESENVOLVIMENTO SUSTENTÁVEL DE POÇO VERDE'),
    ('ACRACDB', 'ASSOCIAÇÃO COMUNITARIA RURAL DE ALTO DOS CARNEIROS DE BAIXO'),
    ('ADCCRC', 'ASSOCIAÇÃO DE DESENVOLVIMENTO COMUNITÁRIO RURAL DE CASTANHO'),
    ('ACRJGA', 'ASSOCIAÇÃO COMUNITARIA RURAL JOSE GALDINO DE ANDRADE'),
    ('ACRRR', 'ASSOCIAÇÃO COMUNITARIA RURAL DO RIACHÃO DOS RIBEIROS'),
    ('ACJAOSDB', 'ASSOCIAÇÃO COMUNITARIA JOAQUIM ALVES OE SOUZA DO DISTRITO DE BANDARRA'),
    ('ACRSJOPP', 'ASSOCIACAO COMUNITARIA RURAL DE SAO JOSE OPERARIO DE PILOES'),
    ('APRPT', 'ASSOCIAÇÃO DOS PRODUTORES RURAI DO POVOADO DE TIMBAUBA'),
    ('ACRSJOP', 'ASSOCIAÇÃO COMUNITÁRIA RURAL DE SÃO JOSÉ OPERÁRIO DE PILÕES'),
    ('ACRNSC', 'ASSOCIAÇÃO COMUNITARIA RURAL NOSSA SENHORA DA CONCEIÇÃO'),
    ('ACRJLDS', 'ASSOCIAÇÃO COMUNITARIA RURAL JOÃO LUIZ DE SOUSA'),
    ('ACRSS', 'ASSOCIAÇÃO COMUNITÁRIA RURAL SÃO SEBASTIÃO'),
    ('ADCLD', 'ASSOCIAÇÃO DE DESENVOLVIMENTO COMUNITÁRIO DE LAGOA DE DENTRO'),
    ('AAAJ', 'ASSOCIAÇÃO DOS AGRICULTORES DO ASSENTAMENTO JATOBÁ'),
    ('AADRAI', 'ASSOCIAÇÃO DOS ASSENTADOS DA REFORMA AGRARIA DO ASSENTAMENTO IMACULADA'),
    ('AAZ', 'ASSOCIACAO DOS AGRICULTORES DO SITIO ZEQUINHA'),
    ('ATREZ', 'ASSOCIAÇÃO DOS TRABALHADORES RURAIS EMILIANO ZAPATA'),
    ('ATRICSC', 'ASSOCIAÇÃO DOS TRABALHADORES RURAIS IMACULADA DO MUNICÍPIO DE SOUSA CANAÃ'),
    ('ACRX', 'ASSOCIAÇÃO COMUNITÁRIA DE RIACHO DOS XAVIER'),
    ('ACPRCA', 'ASSOCIAÇÃO COMUNITÁRIA DOS PRODUTORES RURAIS DE CAMPO ALEGRE'),
)

UNIDADES = (
    ('Mês', 'Mês'),
    ('und', 'Unidade'),
    ('m²', 'Metro Quadrado'),
    ('m³', 'Metro Cúbico'),
    ('m', 'Metro'),
    ('kg', 'Kilograma'),
    ('T', 'Toneladas')
)

STATUS_CHOICES = (
    ('EXEC', 'Em Execução'),
    ('PARA', 'Paralisado'),
    ('NAO_INI', 'Não Iniciado'),
    ('CONCL', 'Concluído'),
)


TIPOS_ARQUIVO_CHOICES = (
        ('ORCAMENTO', 'Planilha de Orçamento'),
        ('IMAGENS', 'Imagens da Obra'),
        ('MEMORIA', 'Memória de Cálculo'),
        ('PLANTA', 'Planta'),
        ('CRONOGRAMA', 'Cronograma Executivo'),
    )





